# Generated by Django 6.0.2 on 2026-02-08 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='featured_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
