# Generated by Django 6.0.2 on 2026-02-08 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_project_featured_at'),
    ]

    operations = [
    ]
